### ISSUE TITLE
troll report ignoring

### ISSUE THREAD

**Issue by Mahanzamabi** [ShaloOS/ShaloOS#4]
### Os Is Very Very Bad I am Run Shalo in windows see error
run in linux see error
error1:not find dir
error2:not find rich
**plase create install file!**
🙏🙏

**Comment by ignGeri** [comment]
Hello the rich issue can be fixed with
```pip install rich```
can you please send us a crash log?

**Comment by Mahanzamabi** [comment]
Hi I was inside when I ran the program Inside f ile This was the pwd.py
file I saw Temp / not found

**Comment by ignGeri** [comment]
Can you tell me what operating system you use and the crash log (the error it **exactly** prints)

**Comment by ignGeri** [comment]
can you tell me what exactly does it print out?

**Comment by ignGeri** [comment]
Issue closed due to trolling
